### ISSUE TITLE
does this plugin work?

### ISSUE THREAD

**Issue by boxxxie** [senecajs/seneca-redis-queue-transport#1]
i tried running your tests and they tend to fill my screen with errors.
i do have redis installed, and i'm using it for other parts of my code, so i don't think it's the issue.

**Comment by iantocristian** [comment]
Yeah, it should work. What sort of errors are you seeing?

**Comment by iantocristian** [comment]
```
npm install
npm test
```

**Comment by iantocristian** [comment]
@boxxxie please add a proper bug report if you have issues
