### ISSUE TITLE
Using a redies queue is considered as a async microservices architecture

### ISSUE THREAD

**Issue by edwinallenz** [senecajs/seneca-redis-queue-transport#23]
I'm thinking of building an async ms architecture with seneca. Async in terms of, instead of doing a REST request and waiting for the response synchronously, I need a pattern where a client/consumer can queue jobs to a group of workers. My question is, if I use this redis queue transport, the seneca `act` as a consumer will queue de job in redis and then I can have multiple seneca instances with `add` that will work as multiple workers that executes jobs in the redis queue asynchronously.

**Comment by mcdonnelldean** [comment]
Correct. You can have multiple listeners. See https://github.com/nodezoo/nodezoo-dequeue

We had to add a little hack because right now the queue takes items as fast as it can get them, this caused issues for use due to using a mesh network. Something we are hoping to resolve soon.

**Comment by edwinallenz** [comment]
That's great I will use this pattern to decouple a set of responsibilities that are tied to hubot chatbot scripts :100:
